baseURL: "https://blog.annahri.com/"
title: Annahri Ngelinux
paginate: 8

languageCode: 'id-id'
defaultContentLanguage: 'id'
timeZone: 'Asia/Jakarta'

theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: An-Nahri | Linux Blogger
  description: "Annahri Blog"
  keywords: [Blog, Portfolio]
  author: [ "Muhammad Ahfas An Nahri" ]
  # images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "2 January 2006"
  defaultTheme: dark # dark, light
  disableThemeToggle: true

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true

  assets:
    bismillah: "17WTklzV4j4O0PMOeHtAqjXjXd9hrtfbT"
    disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "https://s3-jak01.storageraya.com/ahf-testcdn/favicon.ico"
    # favicon16x16: "<link / abs url>"
    # favicon32x32: "<link / abs url>"
    # apple_touch_icon: "<link / abs url>"
    # safari_pinned_tab: "<link / abs url>"
    custom_css: [ "css/custom_papermod.css" ]

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: blog.annahri.com
    subtitle: "InsyaAllah, blog ini berisi artikel-artikel tentang linux berbahasa Indonesia."
    imageUrl: "https://s3-jak01.storageraya.com/ahf-testcdn/img/annahri_logo.svg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: Logo Saya
    buttons:
      - name: Artikel
        url: posts
      - name: Tag
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Assalamualaikum.."
    Content: >
      _InsyaAllah_, blog ini berisi dan akan berisikan artikel-artikel yang mayoritasnya membahas seputar Linux dan mungkin yang lainnya, dalam bahasa Indonesia 🇮🇩.
      Semoga bermanfaat, _barakallahufiikum_.

  socialIcons:
    - name: linkedin
      url: "https://linkedin.com/in/an-nahri"
    - name: stackoverflow
      url: "https://unix.stackexchange.com/users/245871/annahri"
    - name: github
      url: "https://github.com/annahri"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/annahri/blog.annahri.com/tree/main/content"
    Text: "Sarankan Perubahan" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: archives
      name: Arsip
      url: /arsip/
      weight: 5
    - identifier: categories
      name: Kategori
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tagar-tagar
      url: /tags/
      weight: 20
    - identifier: search
      name: Pencarian
      url: /cari/
      weight: 30

markup:
    highlight:
        #anchorLineNos: true
        codeFences: true
        guessSyntax: true
        #noClasses: false
        pygmentsUseClasses: true
        #lineNos: true
        style: dracula

taxonomies:
  category: categories
  tag: tags
  series: series

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
